org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Fabric Properties
  # check these on https://fabricmc.net/develop
  minecraft_version=26.3-rc-3
  loader_version=0.19.5
  fabric_version=0.160.5+26.3

# Mod Properties
  group=com.presencefootsteps
  displayname=Presence Footsteps
  authors=Hurricaaane (Ha3), Sollace
  description=An overly complicated sound mod
  url=http://presencefootsteps.ha3.eu

# Publishing
  minecraft_version_range=>=26.3-rc.3
  modrinth_loader_type=fabric
  modrinth_project_id=rcTfTZr3

# Testing
  use_minelp=0

# Dependencies
  modmenu_version=21.0.0-beta.1
  minelp_version=4.16.0-beta.5+26.1
  kirin_version=1.22.2-beta.1+26.3
